### PR TITLE
Implement regenerate for Sponge.

### PR DESCRIPTION
**Pull request by clienthax**

### CODE REVIEW

**Comment by wizjany** [comment]
You realize sponge doesn't run on 1.13 right? How did you even test this change?

**Comment by clienthax** [comment]
@wizjany Tested it on the 6.1.9 code, the sponge api hasn't changed since and only a couple of worldedit class names were refactored, logically the code is the same and should function as such.

Is there another branch i can PR this to for 1.12.2 ?

**Comment by wizjany** [comment]
https://github.com/EngineHub/WorldEdit/tree/forge-archive/1.12.2

**Comment by kenzierocks** [comment]
FYI, GitHub has the ability to [change base branches for PRs](https://help.github.com/en/articles/changing-the-base-branch-of-a-pull-request), so it's not necessary to make a new PR. I'll close this in favor of #486.

**Pull request closed without merging**
