### PR TITLE
Fabric 1.16

### PR DESCRIPTION
**Pull request by octylFractal**
This is a mostly-complete update to 1.16 for Fabric.

The biggest change is the brand new regen algorithm, which is much faster & safer than before due to loading a new server world from the ground up, and then submitting load tasks all at once for maximum async loading.

This PR will become un-drafted when 1.16 is released and this PR is updated to it.

### CODE REVIEW

**Comment by phemmer** [comment]
I see from the description that you consider this "mostly-complete". Is it expected to be at least somewhat functional at this point? If not, then you can ignore the rest of this, and I'll go wait for a release.

Anyway, I'm starting to experiment with 1.16, and attempting to load WorldEdit ([build #5051](https://builds.enginehub.org/job/worldedit/14574)) throws an exception:
```
Exception in thread "main" java.lang.RuntimeException: Failed to read accessWidener file from mod worldedit
	at net.fabricmc.loader.transformer.accesswidener.AccessWidener.loadFromMods(AccessWidener.java:60)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:130)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: java.lang.RuntimeException: Namespace (named) does not match current runtime namespace (intermediary)
	at net.fabricmc.loader.transformer.accesswidener.AccessWidener.read(AccessWidener.java:78)
	at net.fabricmc.loader.transformer.accesswidener.AccessWidener.loadFromMods(AccessWidener.java:58)
	... 2 more
```

This is with Minecraft 1.16-pre5, & Fabric-loader 0.8.7+build.201-1.16-pre5

**Comment by octylFractal** [comment]
I mistakenly though Fabric would map it for me by default, fixed.

**Comment by i509VCB** [comment]
Just a heads up, commands are a crapshoot right now and where you register commands currently (during server start) is too late for anyone using worldedit in functions [all functions that call worldedit fail].

This is a big issue on fabric api as well so I am trying to find a solution to this issue.

**Comment by octylFractal** [comment]
Yea, not really related to this PR, you can file an issue if you want but IIRC it doesn't even work on Bukkit, we need to reload the resource manager after we register or get Mojang to change when the commands are serialized to functions.

**Pull request merged**
