### PR TITLE
Added Bamboo within the tree tool

### PR DESCRIPTION
**Pull request by JorisN-21**
Based on issue 2009:
https://github.com/EngineHub/WorldEdit/issues/2009
The tree tool couldn't generate a bamboo-plant so I added this within the tool itself

I based the generation on naturally occuring bamboo plants, the plants have a random height between 2-16 blocks
ideal for making mixed bamboo forest 

Kind regards

joris

### CODE REVIEW

**Comment by me4502** [comment]
As I alluded to in this screenshot, you should be able to do this without manually placing blocks; you should be able to piggyback on Minecraft's Bamboo generator. This is generally preferred as it'll always give a more accurate result to natural Minecraft bamboo. If a platform (such as Bukkit) did not support spawning Bamboo, then it might make sense to add a fallback
4888E3E4-F8FE-49A7-B6BF-CC2F729BC38A_1_105_c

**Comment by JorisN-21** [comment]
okay thanks for the feedback !

**Comment by me4502** [comment]
Closing due to inactivity and significant issues that haven't been addressed

**Comment by JorisN-21** [comment]
😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭
________________________________
Van: Maddy Miller ***@***.***>
Verzonden: donderdag 11 januari 2024 13:45
Aan: EngineHub/WorldEdit ***@***.***>
CC: JorisN-21 ***@***.***>; Author ***@***.***>
Onderwerp: Re: [EngineHub/WorldEdit] Added Bamboo within the tree tool (PR #2326)


Closing due to inactivity and significant issues that haven't been addressed

**Pull request closed without merging**
