### PR TITLE
Use DFU for updating MCEdit schematics

### PR DESCRIPTION
**Pull request by Brokkonaut**
See https://github.com/EngineHub/WorldEdit/issues/2370

### CODE REVIEW

**Comment by me4502** [comment]
How heavily has this been tested? I'd inclined to merge this if it does appear to work better, although would ideally prefer to try testing whatever issues led to them being skipped in the first place (if @wizjany remembers what they were)

**Comment by wizjany** [comment]
I think some of the issues were due to running the legacy fixers (i.e. from DV=-1) as opposed to using our inbuilt compathandlers in tandem with DFU from DV=1.13, as this PR does. That said DFU has always been finicky and it may be worth doing some error handling and throwing out tags that cause exceptions just in case?

**Comment by me4502** [comment]
We could also add DFU as a side effect that can be turned off in //perf as a follow up too, if there are some instances where it's problematic to have it enabled

**Comment by me4502** [comment]
Closed in https://github.com/EngineHub/WorldEdit/commit/392393552874bc8d9ceecfe984a33e41ba55bbe4, thanks - I ended up rebasing this against master rather than putting it into 7.2.x due to potential risk of the change.

**Pull request closed without merging**
