### PR TITLE
Added suggestions to a lot of factory-related commands

### PR DESCRIPTION
**Pull request by me4502**
Few talking points:

Patterns/Masks are real complex and allow multiple to be used. This does not handle that, it's just a basic level of functionality to cover simple cases of setting a block. Not sure how well Piston/MC supports this.

In vanilla commands (/fill) it appears to provide a tonne more feedback with usage/command sections/colours - is this possible to achieve?

Also - for suggesting completions on BlockState properties, idk how that'll be achieved in terms of how the system works.

### CODE REVIEW

**Comment by wizjany** [comment]
In general, I dislike the no-arg `getSuggestions` method. If we pass in the current context, each factory can generate a lot more useful suggestions, including parsing the current block to generate states for that block (e.g., if `slab[ty` is types, we can suggest `slab[type=top]` or `slab[type=bottom]` or even `slab[type=top,`)

**Comment by DarkArc** [comment]
I think that's a fair point @wizjany. Also definitely have concerns about insanely log tab complete lists if the entire registry is up for tab complete -- though maybe I'm just misunderstanding how this would work.

**Comment by wizjany** [comment]
the client has a scrollable list. https://i.imgur.com/7Intbb3.png

**Comment by DarkArc** [comment]
Witchcraft, so fancy compared to the olden days I'm used to lol

**Comment by me4502** [comment]
Yeah massive lists isn't an issue - vanilla commands have the same issues tbh. 

As for the vanilla stuff, yeah - I'm aware we're not sending a graph to the client. Was just wondering if there were ways around some of it.

**Pull request merged**
