### PR TITLE
Fix onLeftClickAir click event missing.

### PR DESCRIPTION
**Pull request by Vaelot**
This pull request is fixing fabric-specific issue #1490.

### CODE REVIEW

**Comment by wizjany** [comment]
iirc the issue with this is that it triggered a lot more than it should, including for some right click actions.

**Comment by Vaelot** [comment]
> iirc the issue with this is that it triggered a lot more than it should, including for some right click actions.

SO, the reason why remove this part is because onLeftClickAir triggers multiple times, which I didn't realized that(I though it might be my hardware issue, especially on my mouse.)

But I'm afraid just removing those lines and left navtool as an uncomfortable feature (for fabric server) is worse than just left that bug.

I think that behavior is not that much as severe as crash(...or there's something missed issues?) That was the reason why I pulled this request.

**Comment by octylFractal** [comment]
Left click air is basically non-functional in 1.16 as-is, I haven't had time to figure out if we can get a reliable method, but firing on both left and right is unacceptable, and considering that Bukkit never has a left click air, I don't think it's much of a loss for now.

**Comment by Vaelot** [comment]
I think this PR is part of a difference of POV.

> Left click air is basically non-functional in 1.16 as-is, 

I didn't realize that was non functional; I had no idea about both how fabric api is working and CoC of worldedit. I just thought that #1490 was annoying me, so I revert those changes and PRed it.

> ...I haven't had time to figure out if we can get a reliable method, but firing on both left and right is unacceptable, and considering that Bukkit never has a left click air, I don't think it's much of a loss for now.

I agree with you. Maybe this PR is not respecting your progresses. I think I should close this PR.

**Pull request closed without merging**
