### PR TITLE
Create Download.html

### PR DESCRIPTION
**Pull request by Poodleschool**
This will take you to download the w/e file (This is a sample, Replace the link with the official one)

### CODE REVIEW

**Comment by Poodleschool** [comment]
Whyd you close it

**Comment by octylFractal** [comment]
A link to a random Dropbox is highly suspect.

**Comment by Poodleschool** [comment]
Well whatd I say
You should replace it

**Comment by Poodleschool** [comment]
with the spigot mc link

**Comment by zml2008** [comment]
1. there's no spigot link 
2. WE already has a downloads site - this is just a random file in a repo, not a website

**Pull request closed without merging**
