### PR TITLE
Fix flipping of chests and stairs

### PR DESCRIPTION
**Pull request by Brokkonaut**

### CODE REVIEW

**Comment by wizjany** [comment]
will close https://dev.enginehub.org/youtrack/issue/WORLDEDIT-4004

**Comment by me4502** [comment]
Is it worthwhile ensuring that these "type" and "shape" properties have the values that we expect them to? I can see these being rather common property names amongst mods and future MC blocks.

**Comment by Brokkonaut** [comment]
Ok, I added a check for that

**Comment by Tsoccerguy3** [comment]
I just compiled the plugin for 7.01 and 7.1 . The fix is working for //flip North , South , East and West . 
//flip up and flip down are still broken .

**Comment by Tsoccerguy3** [comment]
> 
> 
> Ok, I added a check for that

better test //flip up and //flip down

**Comment by Brokkonaut** [comment]
> better test //flip up and //flip down

Should be fixed now

**Comment by me4502** [comment]
Thanks

**Pull request merged**
